version: "3.9"

services:
  inventory-server:
    build: .
    container_name: inventory_server
    ports:
      - "50:50"
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    command: ["node", "index.js", "--host", "0.0.0.0", "--port", "50", "--cache", "./cache"]
